name: C/C++ CI

on:
  push:
    branches: [ "master" ]

jobs:
  RunTests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install package
      run: |
        sudo apt-get update
        sudo apt-get -y install pkg-config check

    - name: Tests
      run: make test
      
